### ISSUE TITLE
How will this environment variable used?

### ISSUE THREAD

**Issue by xuyuji9000** [hust-sh/eventhub#4]
https://github.com/hust-sh/eventhub/blob/d4f69e0fcdbed283dc232569962183c32df99d24/docker-compose.yml#L11

**Comment by yangluoshen** [comment]
It takes no use right here.
But considering we may have dev-environment, test-environemnt, online-environment in the future.
And different environment has different configuration, we can use this param to distinct(for example os.GetEnv('ENV') is fine).

**Comment by xuyuji9000** [comment]
okey, python [palmface]
